<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.2</Version>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
		<Description>易物联协议</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Quick.Protocol" Version="2.6.9" />
  </ItemGroup>

</Project>
